# Generated by Django 4.2.6 on 2023-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.IntegerField()),
                ('namaProduk', models.CharField(max_length=255)),
                ('bs', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
