# Generated by Django 4.2.6 on 2023-10-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0002_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaProduk', models.CharField(max_length=255)),
                ('kode', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('jumlah', models.IntegerField()),
                ('hargaPokok', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_file',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_name',
        ),
        migrations.AddField(
            model_name='sales',
            name='fileSales',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sales',
            name='periode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
