# Generated by Django 4.2.6 on 2023-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royal', '0003_salesdetail_remove_sales_sales_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetail',
            name='salesId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='hargaPokok',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
